server:
  port: 8081


#person:
#  age: 19
#  boss: false
#  birth: 2019/7/1
#  maps: {k1: v1,k2: 12}
#  lists:
#    - Lishi
#    - lidongmei
#  dog:
#    name: tom
#    age: 2
#  last-name: Smith Field